services:
  app:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mkdocs:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./docs:/docs
    command: ["mkdocs", "serve", "--dev-addr=0.0.0.0:8000"]

volumes:
  db-data:
