site_name: 'API Documentation'
site_description: 'Documentation for the FastAPI project'
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
nav:
  - Home: index.md
  - API Reference:
      - Users: docs/users.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
