apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: selber/app2:1.1
        env:
        - name: SECRET_KEY
          value: 
        - name: POSTGRES_HOST
          value: 
        - name: POSTGRES_DB
          value: 
        - name: POSTGRES_USER
          value: 
        - name: POSTGRES_PASSWORD
          value: 
        - name: ALGORITHM
          value: 
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: 
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi
